package com.isartdigital.perle.ui.hud.dialogue;

import com.isartdigital.perle.game.AssetName;
import com.isartdigital.perle.game.managers.DialogueManager;
import com.isartdigital.perle.game.managers.SaveManager;
import com.isartdigital.perle.utils.Interactive;
import com.isartdigital.utils.events.MouseEventType;
import com.isartdigital.utils.ui.smart.SmartButton;
import com.isartdigital.utils.ui.smart.SmartComponent;
import com.isartdigital.utils.ui.smart.SmartScreen;
import com.isartdigital.utils.ui.smart.TextSprite;
import flump.library.SpriteSymbol;
import pixi.core.display.Container;
import pixi.flump.Sprite;

typedef Dialogue = {
	var npc:String;
	var npc_text:String;
}	
/**
 * ...
 * @author Alexis
 */
class DialogueUI extends SmartScreen 
{
	
	
	private var btnNext:SmartButton;
	private var npc_name:TextSprite;
	private var npc_speach:TextSprite;
	public static var numberOfDialogue:Int;
	public static var firstToSpeak:String;
	
	//Array of the dialogue
	public static var lNpc_dialogue_ftue:Array<Array<Array<String>>>;
	
	/**
	 * instance unique de la classe FtueUI
	 */
	private static var instance: DialogueUI;
	
	/**
	 * Retourne l'instance unique de la classe, et la crée si elle n'existait pas au préalable
	 * @return instance unique
	 */
	public static function getInstance (): DialogueUI {
		if (instance == null) instance = new DialogueUI();
		return instance;
	}
	
	/**
	 * constructeur privé pour éviter qu'une instance soit créée directement
	 */
	private function new(pID:String=null) 
	{
		super(AssetName.FTUE);
		modal = null;
		setWireframe();
	}
	
	/**
	 * Close Ftue
	 */
	private function closeFtue() {
		btnNext.removeAllListeners();
		DialogueManager.removeDialogue();
	}
	
	/**
	 * Set all the variables to the wireframe
	 */
	private function setWireframe():Void {
		npc_name = cast(getChildByName(AssetName.FTUE_NAME), TextSprite);	
		npc_speach = cast(getChildByName(AssetName.FTUE_SPEACH), TextSprite);	
		btnNext = cast(getChildByName(AssetName.FTUE_BUTTON), SmartButton);
		Interactive.addListenerClick(btnNext, onClickNext);
	}
	
	/**
	 * Button
	 */
	private function onClickNext():Void {
		DialogueManager.endOfaDialogue();
	}
	
	/**
	 * Create Text generated by the map
	 */
	public function createText(pNumber:Int, pNpc:String):Void {
		
		npc_name.text = pNpc;
		npc_speach.text = DialogueManager.npc_dialogue_ftue[pNumber-1][0][1];
		changeAlpha(DialogueManager.npc_dialogue_ftue[pNumber-1][0][0],pNpc);
	}
	
	/**
	 * function to change the alpha of the NPC who talk
	 * @param	pName of NPC
	 */
	private function changeAlpha(pNpc:String,pNpcCheck:String) {
		if (pNpc == pNpcCheck) {
			getChildByName(AssetName.FTUE_HEAVEN).alpha = 0.5;
			getChildByName(AssetName.FTUE_HELL).alpha = 1;
		}
		else {
			getChildByName(AssetName.FTUE_HEAVEN).alpha = 1;
			getChildByName(AssetName.FTUE_HELL).alpha = 0.5;
		}
	}

	/**
	 * détruit l'instance unique et met sa référence interne à null
	 */
	override public function destroy (): Void {
		Interactive.removeListenerClick(btnNext, onClickNext);
		instance = null;
		super.destroy();
	}

}