package com.isartdigital.perle.ui.hud.dialogue;

import com.isartdigital.perle.game.AssetName;
import com.isartdigital.perle.game.managers.DialogueManager;
import com.isartdigital.perle.game.managers.TweenManager;
import com.isartdigital.perle.utils.Interactive;
import com.isartdigital.utils.game.GameStage;
import com.isartdigital.utils.ui.smart.SmartButton;
import com.isartdigital.utils.ui.smart.SmartComponent;
import com.isartdigital.utils.ui.smart.SmartScreen;
import com.isartdigital.utils.ui.smart.TextSprite;
import com.isartdigital.utils.ui.smart.UISprite;
import pixi.core.math.Point;

	
/**
 * ...
 * @author Alexis
 */
class DialoguePoppin extends SmartScreen 
{
	private static inline var NEUTRAL_EXPRESSION:String = "_Neutral";
	private static inline var HELL_NPC:String = "Demona";
	private static inline var ON_ALPHA:Float = 1;
	private static inline var OFF_ALPHA:Float = 0.2;
	
	private var scenarioAngel:SmartComponent;
	private var scenarioHell:SmartComponent;
	private var actionAngel:SmartComponent;
	private var actionHell:SmartComponent;
	private var icon5:SmartComponent;
	private var icon6:SmartComponent;
	private var btnNext:SmartButton;
	private var btnEnd:SmartButton;
	private static var windowOpened:SmartComponent;
	
	//private var npc_name:TextSprite;
	private var npc_speach:TextSprite;
	private var npc_right:String;
	private var npc_left:String;
	public static var wasAction:Bool;
	
	public static var numberOfDialogue:Int;
	public static var firstToSpeak:String;
	
	//Array of the dialogue
	public static var lNpc_dialogue_ftue:Array<Array<Array<String>>>;
	
	public static var allExpressionsArray:Array<String>;
	
	/**
	 * instance unique de la classe DialoguePoppin
	 */
	private static var instance: DialoguePoppin;
	
	/**
	 * Retourne l'instance unique de la classe, et la crée si elle n'existait pas au préalable
	 * @return instance unique
	 */
	public static function getInstance (): DialoguePoppin {
		if (instance == null) instance = new DialoguePoppin();
		return instance;
	}
	
	/**
	 * constructeur privé pour éviter qu'une instance soit créée directement
	 */
	private function new() 
	{
		super(AssetName.FTUE);
		modal = null;
		setWireframe();
	}
	
	/**
	 * Close Ftue
	 */
	private function closeFtue() {
		DialogueManager.removeDialogue();
	}
	
	/**
	 * Set all the variables to the wireframe
	 */
	private function setWireframe():Void {
		scenarioAngel = cast(getChildByName(AssetName.FTUE_SCENARIO_WINDOW_HEAVEN), SmartComponent);
		scenarioHell = cast(getChildByName(AssetName.FTUE_SCENARIO_WINDOW_HELL), SmartComponent);
		actionAngel = cast(getChildByName(AssetName.FTUE_ACTION_HEAVEN), SmartComponent);
		actionHell = cast(getChildByName(AssetName.FTUE_ACTION_HELL), SmartComponent);
		icon5 = cast(getChildByName(AssetName.FTUE_ICON_5), SmartComponent);
		icon6 = cast(getChildByName(AssetName.FTUE_ICON_6), SmartComponent);
		
		btnNext = cast(getChildByName(AssetName.FTUE_SCENARIO_BUTTON), SmartButton);
		Interactive.addListenerClick(btnNext, nextStep);
		btnEnd = cast(getChildByName(AssetName.FTUE_SCENARIO_BUTTON_END), SmartButton);
		Interactive.addListenerClick(btnEnd, nextStep);
		setAllFalse();
	}
	
	private function nextStep():Void{
		DialogueManager.endOfaDialogue();
	}
	
	/**
	 * Create Text generated by the map
	 */
	public function createText(pNumber:Int, pNpc:String, pPicture:String, pExpression:String, isAction:Bool, dialogueSaved:Int):Void {
		setAllFalse();
		checkIfVisible(pNpc, pExpression, isAction,dialogueSaved);
		checkIfIcons(pNumber);
		
		if (npc_speach != null)
		npc_speach.text = DialogueManager.npc_dialogue_ftue[pNumber - 1][0][1];
		addEffectToDialogueSpawn(isAction,pNpc,pNumber);
	}
	
	private function checkIfVisible(pNpc:String, pExpression:String, isAction:Bool, dialogueSaved:Int):Void {
		var lPanel:SmartComponent;
		if (isAction) {
			if (pNpc == HELL_NPC)
				lPanel = actionHell;
			else
				lPanel = actionAngel;
		}
		else {
			if (pNpc == HELL_NPC)
				lPanel = scenarioHell;
			else
				lPanel = scenarioAngel;
			checkWichButton(dialogueSaved);
		}
		lPanel.visible = true;
		setTextWf(isAction, lPanel);
	}
	
	private function checkWichButton(dialogueSaved:Int) {
		if (DialogueManager.steps[dialogueSaved].endOfFtue || DialogueManager.steps[dialogueSaved].endOfSpecial || DialogueManager.steps[dialogueSaved].endOfAltar || DialogueManager.steps[dialogueSaved].endOfCollectors || DialogueManager.steps[dialogueSaved].endOfFactory || DialogueManager.steps[dialogueSaved].endOfMarketing || DialogueManager.steps[dialogueSaved].endOfSpecial)
			btnEnd.visible = true;
		else
			btnNext.visible = true;
		Hud.isHide = false;
	}
	
	private function addEffectToDialogueSpawn(pTypeOfDialogueIsAction:Bool, pNpc:String, pNumberOfDialogue:Int) {
		
		if (pTypeOfDialogueIsAction) {
			wasAction = true;
			TweenManager.upperToRealPos(this);
		}
		else if (wasAction) {
			TweenManager.scaleGrow(this,true);
			wasAction = false;
		}
	}
	
	private function setTextWf(isAction:Bool,pPanel:SmartComponent) {
		npc_speach = cast(SmartCheck.getChildByName(pPanel, AssetName.FTUE_SCENARIO_SPEACH), TextSprite);
	}
	
	private function checkIfIcons(pDialogueNumber:Int) {
		switch(pDialogueNumber) {
			case 5 : icon5.visible = true;
			case 6 : icon6.visible = true;
		}
	}
	
	public function getNpcHeavenPos():Point {
		var lNpc:UISprite = cast(SmartCheck.getChildByName(scenarioAngel, "Window_NPC_Heaven_Neutral"), UISprite);
		var lPos:Point = GameStage.getInstance().getFtueContainer().toLocal(lNpc.position);
		return lPos;
	}
	
	public function setAllFalse():Void {
		scenarioAngel.visible = false;
		scenarioHell.visible = false;
		actionAngel.visible = false;
		actionHell.visible = false;
		icon5.visible = false;
		icon6.visible = false;
		btnNext.visible = false;
		btnEnd.visible = false;
	}
	
	/**
	 * détruit l'instance unique et met sa référence interne à null
	 */
	override public function destroy (): Void {
		Interactive.removeListenerClick(btnNext, nextStep);
		Interactive.removeListenerClick(btnEnd, nextStep);
		instance = null;
	}

}